export { ReviewFindingSchema, SEVERITIES } from './model/schema'
export type { DiffSide, FindingCategory, ReviewFinding, Severity } from './model/schema'
export { CATEGORY_LABEL, SEVERITY_LABEL } from './model/labels'
export { anchorLine, bySeverity, groupFindingsByLine } from './lib/anchor'
export type { FindingsByLine } from './lib/anchor'
export { ReviewCommentThread } from './ui/ReviewCommentThread'
export { SeverityBadge } from './ui/SeverityBadge'
